### ISSUE TITLE
Issue with building heights when adding terrain

### ISSUE THREAD

**Issue by nadjabaden** [AntonelloDN/Morpho#21]
Hi Antonello,

I've been having an issue when adding terrain within morpho: the model is not translated correctly into the Envi-met database as some of the building starting heights shift. 

I posted the topic here with a more detailed explanation:
http://www.envi-hq.com/viewtopic.php?f=35&t=5605&sid=373d351e242279ef73cd42a4629c8065

I'm not sure what the issue could be, but it is important that I include the terrain in this case.

Thanks,
Nadja

**Comment by AntonelloDN** [comment]
Hi @nadjabaden,
Can you check following [rules](https://github.com/AntonelloDN/Morpho/wiki/1.-Grasshopper-plugin#geometry-mapping)?
Can you share only the Rhino geometries so I can check It? Thanks

**Comment by nadjabaden** [comment]
Hi @AntonelloDN,

Okay thanks, I will have a look. These are the Rhino geometries:
 [Envimet model geometry.zip](https://github.com/AntonelloDN/Morpho/files/13558715/Envimet.model.geometry.zip)

I also had another question concerning this model. The Site that I'm analysing contains elevated glazed buildings with concrete slab walkways and roofs that have an overhang. For now, I have simplified these by extending the buildings to the edge of the overhang and modelling the walkways as "buildings" with a 1 m thickness. Is there a better/more accurate way to model this using morpho, such as being able to input the concrete slabs as a singular element rather than a "building"?

![Buildings](https://github.com/AntonelloDN/Morpho/assets/152899591/61ae8a2e-a80c-49ee-94f7-9c1f36396dc6) 
![Buildings 2](https://github.com/AntonelloDN/Morpho/assets/152899591/607f7101-1d63-4e1c-89fe-7c6e0eaad8f9)

**Comment by nadjabaden** [comment]
Hi again @AntonelloDN,
I was wondering if you've managed to take a look at the rhino geometries?

From the rules, I see that "All geometries except the terrain must be on the World XY Plane." I tried doing it this way; however, I'm still having issues with the heights. I guess the fact that most buildings are elevated above the ground is causing some difficulties. It also seems that no 2D or 3D plants can be placed underneath elevated buildings, as they get projected above the building, is there a way around this? Or do these need to be removed?

**Comment by nadjabaden** [comment]
Hi again @AntonelloDN,
I was wondering if you've managed to take a look at the rhino geometries?

From the rules, I see that "All geometries except the terrain must be on the World XY Plane." I tried doing it this way; however, I'm still having issues with the heights. I guess the fact that most buildings are elevated above the ground is causing some difficulties. It also seems that no 2D or 3D plants can be placed underneath elevated buildings, as they get projected above the building, is there a way around this? Or do these need to be removed?

**Comment by AntonelloDN** [comment]
Hi @nadjabaden, Sorry for my late reply. It is possible to project buildings using native components of Grasshopper or by script.
You can check the attachment.

[model_with_terrain.zip](https://github.com/AntonelloDN/Morpho/files/13772080/model_with_terrain.zip)


# Clarification about buildings <> terrain
ENVI-met uses this convention to have buildings on the world XY plane. So I have to follow the same rule to be consistent.
You have two options of modeling: 2.5D modeling and 3D modeling.

- 2.5D modeling: You see the world top/down. It is perfect for fast modeling and big models that come from GIS data. It is used by Monde.
- 3D modeling: It is possible to handle complex shapes. You can also model the side of the buildings and vertical variation of the shapes. It has more information and also the size of the file you get is bigger than 2.5D models.

Morpho supports both types. The only limit of the 3D modeling is the absence of the "Single wall" element. 

## 2.5D models buildings <> terrain
- the buildings are placed on world XY plane
- the terrain is modeled with DEM criteria
- ENVI-met project the building onto the terrain automatically using the follow-terrain criteria

## 3D models buildings <> terrain
- the buildings are placed on world XY plane
- the terrain is modeled with DEM criteria
- Morpho can use two kinds of projections: follow-terrain or project by bounding box. The second method uses one corner of the bounding box and calculates the height difference with the terrain without distorting the shape of the building.

## 3D plants, simple plants <> terrain
- The simple plants are part of the 2D world of ENVI-met. They indicate how the soils of ENVI-met is. ENVI-met will project the soil automatically to the terrain. In fact, if you use ENVI-met Spaces you will see that the main way to add soils is by 2D features of Spaces. Simple plants are used pricipally for grass.
- 3D plants follow the same rules of the simple plants. The difference is that they are punctual elements. You can follow one of my sample file where I add a series of 3D plants in the model

Coming back to your sample file:

- I suggest you merge the vertical part of the main buildings. ENVI-met does not have a concept of building splitted vertically. It does not mean that you can't do it with Morpho. But if you want to keep your building splitted vertically you must be careful with the position of the centroid of the grids on your shapes.
- The terrain is very flat. And the small depression is placed on the border of the model where the results are not accurate. You could remove it. If you want to keep it and you want to use 3D modeling system you can use a settings like this:
- ![image](https://github.com/AntonelloDN/Morpho/assets/16763953/d2761537-ea61-4ff2-8d8f-7fa7200edb49)
- The overhang should be modeled as "Single wall" but you should use ENVI-met Spaces. It is not correct to model it as a building because ENVI-met considers it as a real building with a setpoint temperature and a volume of air inside. 

So you can do the main part of the model with Morpho and complete the model with ENVI-met Spaces adding small details (Single walls and windows)

**Comment by nadjabaden** [comment]
Great, thank you for the help @AntonelloDN !
